AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create IAM user with policy and role'

Resources:
  # IAM User
  SampleIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${AWS::StackName}-user'
      Tags:
        - Key: Environment
          Value: Development
        - Key: ManagedBy
          Value: CloudFormation
        - Key: StackName
          Value: !Ref AWS::StackName

  # IAM Policy for the User
  SampleUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-user-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource: '*'
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:DescribeRegions
            Resource: '*'
      Users:
        - !Ref SampleIAMUser

  # IAM Role
  SampleIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Tags:
        - Key: Environment
          Value: Development
        - Key: ManagedBy
          Value: CloudFormation
        - Key: StackName
          Value: !Ref AWS::StackName

  # Inline Policy for the Role
  SampleRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-role-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: '*'
      Roles:
        - !Ref SampleIAMRole

  # Access Key for the User (optional - for programmatic access)
  SampleUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref SampleIAMUser

Outputs:
  IAMUserName:
    Description: Name of the created IAM user
    Value: !Ref SampleIAMUser
    Export:
      Name: !Sub '${AWS::StackName}-UserName'

  IAMUserArn:
    Description: ARN of the created IAM user
    Value: !GetAtt SampleIAMUser.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserArn'

  IAMRoleName:
    Description: Name of the created IAM role
    Value: !Ref SampleIAMRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'

  IAMRoleArn:
    Description: ARN of the created IAM role
    Value: !GetAtt SampleIAMRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  AccessKeyId:
    Description: Access Key ID for the IAM user
    Value: !Ref SampleUserAccessKey

  SecretAccessKey:
    Description: Secret Access Key for the IAM user (keep secure!)
    Value: !GetAtt SampleUserAccessKey.SecretAccessKey