AWSTemplateFormatVersion: '2010-09-09'
Description: IAM user and role with externalized policies

Resources:
  # IAM User
  SampleIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${AWS::StackName}-user'
      Tags:
        - Key: Environment
          Value: Development
        - Key: ManagedBy
          Value: CloudFormation
        - Key: StackName
          Value: !Ref AWS::StackName

  # User Managed Policy (external file)
  UserManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-user-policy'
      PolicyDocument:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: policies/user-policy.json
      Users:
        - !Ref SampleIAMUser

  # IAM Role
  SampleIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref RoleManagedPolicy
      Tags:
        - Key: Environment
          Value: Development
        - Key: ManagedBy
          Value: CloudFormation
        - Key: StackName
          Value: !Ref AWS::StackName

  # Role Managed Policy (external file)
  RoleManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-role-policy'
      PolicyDocument:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: policies/role-policy.json

  # Access Key for the User
  SampleUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref SampleIAMUser

Outputs:
  IAMUserName:
    Value: !Ref SampleIAMUser

  IAMRoleName:
    Value: !Ref SampleIAMRole
